# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: springboot-ci-cd

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment profile name'
        required: true
        default: 'prod'
      version:
        description: 'docker version (default 0.0.1)'
        required: true
        default: '0.0.1'
      port:
        description: 'application port'
        required: true
        default: '5110'

jobs:

  ci-cd:

    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      run: |
        echo "::set-env name=ENVIRONMENT::${{github.event.inputs.environment}}"
        echo "::set-env name=VERSION::${{github.event.inputs.version}}"
        echo "::set-env name=APP_PORT::${{github.event.inputs.port}}"
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        tags: ${{env.ENVIRONMENT}}-${{env.VERSION}}
    - name: deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRIVATE_SSH_HOST }}
        username: ${{ secrets.PRIVATE_SSH_USERNAME }}
        password: ${{ secrets.PRIVATE_SSH_PASSWORD }}
        script: | 
          echo "Hello world!"
          sudo docker stop ${{ secrets.DOCKER_REPO }}_${{env.ENVIRONMENT}}
          sudo docker rm ${{ secrets.DOCKER_REPO }}_${{env.ENVIRONMENT}}
          sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{env.ENVIRONMENT}}-${{env.VERSION}}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{env.ENVIRONMENT}}-${{env.VERSION}}
          sudo docker run -d -p ${{env.APP_PORT}}:${{env.APP_PORT}} -p 10200:10200 -e JAVA_OPTS=-Dspring.profiles.active=${{env.ENVIRONMENT}} --name=${{ secrets.DOCKER_REPO }}_${{env.ENVIRONMENT}} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{env.ENVIRONMENT}}-${{env.VERSION}}

