# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: springboot-ci-cd

on:
  workflow_dispatch

jobs:
  ci-cd:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: py846260131/springboot-ci-cd
        registry: daocloud.io
        tags: $GITHUB_REF
    - name: deloy Docker image remotely
      uses: docker://evaneos/ssh-action:0.1.0
      with:
        hosts: 49.234.113.197
        user: ubuntu
        private_key: ${{ secrets.PRIVATE_SSH_KEY }}
        password: ${{ secrets.PRIVATE_SSH_PASSWORD }}
        commands: | 
          echo "Hello world!"
          # docker stop springboot-test
          # docker rm springboot-test
          # docker pull daocloud.io/py846260131/springboot-ci-cd
          # docker run -d -p 5100:5100 -p 10200:10200 -e JAVA_OPTS=-Dspring.profiles.active=dev --name=springboot-test daocloud.io/py846260131/springboot-ci-cd

